"""Add load_number to FreightOrder

Revision ID: 140da6ff7f39
Revises: b2948bdd0692
Create Date: 2026-07-22 21:39:59.739379

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '140da6ff7f39'
down_revision: Union[str, None] = 'b2948bdd0692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freight_orders', sa.Column('load_number', sa.String(length=100), nullable=True))

    op.create_index(op.f('ix_freight_orders_load_number'), 'freight_orders', ['load_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_orders_load_number'), table_name='freight_orders')

    op.drop_column('freight_orders', 'load_number')
    # ### end Alembic commands ###
